name: CI/CD Pipeline for Auth Service

on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: 🔄 Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ☕ Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 🧰 Cache SonarCloud
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: 📦 Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: 🧪 Ejecutar Tests y Analizar cobertura
        run: mvn clean verify

      - name: 🔍 Análisis SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=hermancortez_auth-service-springboot \
            -Dsonar.organization=hermancortez \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: 🐳 Login en DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: 🏗️ Build imagen Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/auth-service:latest .

      - name: 🚀 Push imagen a DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/auth-service:latest

      - name: 📦 Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: 📁 Crear directorio .kube
        run: mkdir -p $HOME/.kube

      - name: 📄 Decodificar Kubeconfig
        run: echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: ☸️ Desplegar en Kubernetes
        run: |
          kubectl apply -f k8s/configmap.yaml
          kubectl apply -f k8s/deployment-dev.yaml
          kubectl apply -f k8s/service.yaml
